# The cluster configuration is described here. 
# It is used to calculate the workload in scheduler.
cluster:
  name: cHARISMa
  location: HSE, Moscow
  scheduler: Slurm
  operating_system: Linux CentOS
  storage:
    - type: Lustre
      capacity: 848 TB
  management_network: Gigabit Ethernet
  compute_network: InfiniBand EDR 2x100 Gbit/s

nodes:
  - type: A
    count: 16
    model: C4140K
    cpu:
      sockets: 2
      model: Intel Xeon Gold 6152
      cores_per_cpu: 22
      frequency: 2.1-3.7 GHz
    gpu:
      count: 4
      model: NVIDIA Tesla V100
      memory_per_gpu: 32 GB
      interconnect: NVLink
    ram: 768 GB
    storage:
      - type: SSD
        count: 2
        capacity: 240 GB
        raid: 1

  - type: B
    count: 10
    model: C4140K
    cpu:
      sockets: 2
      model: Intel Xeon Gold 6152
      cores_per_cpu: 22
      frequency: 2.1-3.7 GHz
    gpu:
      count: 4
      model: NVIDIA Tesla V100
      memory_per_gpu: 32 GB
      interconnect: NVLink
    ram: 1536 GB
    storage:
      - type: SSD
        count: 2
        capacity: 240 GB
        raid: 1

  - type: C
    count: 3
    model: C4140M
    cpu:
      sockets: 2
      model: Intel Xeon Gold 6240R
      cores_per_cpu: 24
      frequency: 2.4-4.0 GHz
    gpu:
      count: 4
      model: NVIDIA Tesla V100
      memory_per_gpu: 32 GB
      interconnect: NVLink
    ram: 768 GB
    storage:
      - type: SSD
        count: 2
        capacity: 240 GB
        raid: 1

  - type: D
    count: 11
    model: R640
    cpu:
      sockets: 2
      model: Intel Xeon Gold 6248R
      cores_per_cpu: 24
      frequency: 3.0-4.0 GHz
    gpu: null
    ram: 768 GB
    storage:
      - type: SSD
        count: 2
        capacity: 240 GB
        raid: 1

  - type: E
    count: 6
    model: HPE XL675d Gen10+
    cpu:
      sockets: 2
      model: AMD EPYC 7702
      cores_per_cpu: 64
      frequency: 2.0-3.35 GHz
    gpu:
      count: 8
      model: NVIDIA A100
      memory_per_gpu: 80 GB
      interconnect: NVLink (SXM)
    ram: 1 TB
    storage:
      - type: SSD
        count: 2
        capacity: 960 GB
        raid: 1

  - type: F
    count: 2
    model: R760XA
    cpu:
      sockets: 2
      model: Intel Xeon Gold 6426Y
      cores_per_cpu: 16
      frequency: 2.5-4.1 GHz
    gpu:
      count: 2
      model: NVIDIA H100
      memory_per_gpu: 80 GB
      interconnect: NVLink Bridge (PCIe)
    ram: 512 GB
    storage:
      - type: SSD
        count: 2
        capacity: 960 GB
        raid: 1