# The cluster configuration is described here. 
# It is used to calculate the workload in scheduler.
cluster:
  name: cHARISMa
  location: HSE, Moscow
  scheduler: Slurm
  operating_system: Linux CentOS

nodes:
  - type: A
    count: 16
    cpu:
      sockets: 2
      cores_per_cpu: 22
    gpu:
      count: 4

  - type: B
    count: 10
    cpu:
      sockets: 2
      cores_per_cpu: 22
    gpu:
      count: 4
  - type: C
    count: 3
    cpu:
      sockets: 2
      cores_per_cpu: 24
    gpu:
      count: 4

  - type: D
    count: 11
    cpu:
      sockets: 2
      cores_per_cpu: 24
    gpu: null

  - type: E
    count: 6
    cpu:
      sockets: 2
      cores_per_cpu: 64
    gpu:
      count: 8

  - type: F
    count: 2
    cpu:
      sockets: 2
      cores_per_cpu: 16
    gpu:
      count: 2