DBConfigFile = "configs/.env"
schedulerConfigFile = "configs/scheduler.yaml"
serverConfigFile = "configs/server.yaml"
clusterConfigFile = "configs/cluster.yaml"
clusterConfigBackupRoot = "configs/cluster_backups"
academicCalendarRoot = "configs/calendar"
